#!/bin/bash

MAX_MAP_COUNT="$(sysctl vm.max_map_count | cut -d '=' -f 2)"

if (( $MAX_MAP_COUNT < 100000 )); then
   echo "increase max_map_count before test:"
   echo sudo su -c "'echo 655350 > /proc/sys/vm/max_map_count'"
   echo sudo cpupower frequency-set -g performance
   exit 1
fi

pkill geckodriver
pkill firefox

# export TEST_LD_PRELOAD=libmesh2y.so
# export TEST_NAME=mesh
# export MALLOCSTATS=1
# env/bin/python atsy/example/comp_analysis.py -c atsy/example/comp_analysis_conf_speedometer.py --content-processes 0 -b Firefox --per_tab_pause 140 --settle_wait_time 1
# exit

# for suffix in 2y 1y 0y 0n; do
for suffix in 0n 0y 1y 2y; do
    export TEST_LD_PRELOAD=libmesh${suffix}.so
    export TEST_NAME=mesh${suffix}
    export MALLOCSTATS=1
    env/bin/python atsy/example/comp_analysis.py -c atsy/example/comp_analysis_conf_speedometer.py --content-processes 0 -b Firefox --per_tab_pause 140 --settle_wait_time 1

    sleep 5
    pkill geckodriver
    pkill firefox
done

sleep 5
pkill geckodriver
pkill firefox

unset TEST_LD_PRELOAD
unset MALLOCSTATS
export TEST_NAME=jemalloc
env/bin/python atsy/example/comp_analysis.py -c atsy/example/comp_analysis_conf_speedometer.py --content-processes 0 -b Firefox --per_tab_pause 140 --settle_wait_time 1
